#!/bin/bash
#get registrants' info from dn list

#usage : $0 dn_list_file.txt
#usage : $0 ndd.tld

echo -e "<tr><td>FQDN</td><td>Registrar</tr>"
check(){

#quelle extension ?

tld=$(echo "$dn" | awk -F "." '{if (length($3) > 0) print $2"."$3; else print $2}')

#echo $tld

case $tld in

#On check pas les brand TLD

AAA | AARP | ABARTH | ABB | ABBOTT | ABBVIE | ABC | ACCENTURE | ACO | AEG | AETNA | AFL | AGAKHAN | AIG | AIGO | AIRBUS | AIRTEL | AKDN | ALFAROMEO | ALIBABA | ALIPAY | ALLFINANZ | ALLSTATE | ALLY | ALSTOM | AMERICANEXPRESS | AMEX | AMICA | ANDROID | ANZ | AOL | APPLE | AQUARELLE | ARAMCO | ARTE | ATHLETA | AUDI | AUSPOST | AXA | AZURE | BAIDU | BAN | BANANAREPUBLIC | BARCLAYCARD | BARCLAYS | BAUHAUS | BBC | BBT | BBVA | BCG | BENTLEY | BHARTI | BING | BLANCO | BLOOMBERG | BMS | BMW | BNL | BNPPARIBAS | BOEHRINGER | BOND | BOOKING | BOSCH | BOSTIK | BRADESCO | BRIDGESTONE | BROTHER | BUGATTI | CALVINKLEIN | CANON | CAPITALONE | CARTIER | CBA | CBN | CBRE | CBS | CERN | CFA | CHANEL | CHASE | CHINTAI | CHROME | CHRYSLER | CISCO | CITADEL | CITI | CITIC | CLUBMED | COMCAST | COMMBANK | CREDITUNION | CROWN | CRS | CSC | CUISINELLA | DABUR | DATSUN | DELL | DELOITTE | DELTA | DHL | DISCOVER | DISH | DNP | DODGE | DUNLOP | DUPONT | DVAG | EDEKA | EMERCK | EPSON | ERICSSON | ERNI | ESURANCE | ETISALAT | EUROVISION | EVERBANK | EXTRASPACE | FAGE | FAIRWINDS | FARMERS | FEDEX | FERRARI | FERRERO | FIAT | FIDELITY | FIRESTONE | FIRMDALE | FLICKR | FLIR | FLSMIDTH | FORD | FOX | FRESENIUS | FROGANS | FRONTIER | FUJITSU | FUJIXEROX | GALLO | GALLUP | GAP | GBIZ | GEA | GENTING | GLOBO | GMAIL | GMO | GMX | GODADDY | GOLDPOINT | GOODYEAR | GOOG | GOOGLE | GRAINGER | GUARDIAN | GUCCI | HBO | HDFC | HDFCBANK | HERMES | HISAMITSU | HITACHI | HKT | HOMEDEPOT | HONDA | HONEYWELL | HOTMAIL | HSBC | HUGHES | HYATT | HYUNDAI | IBM | IEEE | IFM | IKANO | IMDB | INFINITI | INTEL | INTUIT | IPIRANGA | ISELECT | ITAU | ITV | IVECO | JAGUAR | JAVA | JCB | JCP | JEEP | JPMORGAN | JUNIPER | KDDI | KERRYHOTELS | KERRYLOGISTICS | KERRYPROPERTIES | KFH | KIA | KINDER | KINDLE | KOMATSU | KPMG | KUOKGROUP | LACAIXA | LADBROKES | LAMBORGHINI | LANCASTER | LANCIA | LANCOME | LANDROVER | LANXESS | LASALLE | LATROBE | LECLERC | LEGO | LEXUS | LIAISON | LIDL | LILLY | LINCOLN | LINDE | LIPSY | LIXIL | LOCUS | LOTTE | LPL | LPLFINANCIAL | LUNDBECK | LUPIN | MACYS | MAIF | MAN | MANGO | MARRIOTT | MASERATI | MATTEL | MCKINSEY | METLIFE | MICROSOFT | MINI | MIT | MITSUBISHI | MLB | MORMON | MOVISTAR | MSD | MTN | MTR | MUTUAL | NADEX | NATIONWIDE | NATURA | NBA | NEC | NETFLIX | NEUSTAR | NEWHOLLAND | NEXUS | NFL | NHK | NICO | NIKE | NIKON | NISSAN | NISSAY | NOKIA | NORTHWESTERNMUTUAL | NORTON | NRA | NTT | OBI | OFFICE | OMEGA | ORACLE | ORANGE | PANASONIC | PCCW | PFIZER | PHILIPS | PIAGET | PICTET | PIONEER | PLAYSTATION | POHL | POLITIE | PRAXI | PROGRESSIVE | PRU | PRUDENTIAL | PWC | QUEST | QVC | REDSTONE | RELIANCE | REXROTH | RICOH | RMIT | ROCHER | ROGERS | RWE | SAFETY | SAKURA | SAMSUNG | SANDVIK | SANDVIKCOROMANT | SANOFI | SAP | SAXO | SBI | SBS | SCHAEFFLER | SCHMIDT | SCHWARZ | SCJOHNSON | SCOR | SEAT | SEEK | SENER | SES | SEVEN | SEW | SFR | SHANGRILA | SHARP | SHAW | SHELL | SHRIRAM | SINA | SKY | SKYPE | SMART | SNCF | SOFTBANK | SOHU | SONY | SPIEGEL | STADA | STAPLES | STAR | STARHUB | STATEBANK | STATEFARM | STATOIL | STC | STCGROUP | SUZUKI | SWATCH | SWIFTCOVER | SYMANTEC | TAOBAO | TARGET | TATAMOTORS | TDK | TELECITY | TELEFONICA | TEMASEK | TEVA | TIFFANY | TJX | TORAY | TOSHIBA | TOTAL | TOYOTA | TRAVELCHANNEL | TRAVELERS | TUI | TVS | UBS | UNICOM | UOL | UPS | VANGUARD | VERISIGN | VIG | VIKING | VIRGIN | VISA | VISTA | VISTAPRINT | VIVO | VOLKSWAGEN | VOLVO | WALMART | WALTER | WEATHERCHANNEL | WEBER | WEIR | WILLIAMHILL | WINDOWS | WME | WOLTERSKLUWER | WOODSIDE | WTC | XBOX | XEROX | XFINITY | YAHOO | YAMAXUN | YANDEX | YODOBASHI | YOUTUBE | ZAPPOS | ZARA | ZIP | ZIPPO )

registrar="Brand TLD. Skipping.";;

#cas des GTLD et compatibles
AM | ABLE | ABOGADO | ABUDHABI | AC | ACADEMY | ACCOUNTANT | ACCOUNTANTS | ACTOR | ADS | ADULT | AERO | AF | AFAMILYCOMPANY | AFRICA | AG | AGENCY | AIRFORCE | ALSACE | AMERICANFAMILY | AMFAM | AMSTERDAM | ANALYTICS | APARTMENTS | APP | ARCHI | ARMY | ART | ASDA | ASSOCIATES | AT | ATTORNEY | AUCTION | AUDIBLE | AUDIO | AUTHOR | AUTO | AUTOS | AVIANCA | BABY | BANAMEX | BAND | BANK | BAR | BARCELONA | BAREFOOT | BARGAINS | BASEBALL | BAYERN | BCN | BEATS | BEAUTY | BEER | BERLIN | BESTBUY | BET | BI | BIBLE | BID | BIKE | BINGO | BIO | BIZ | BJ | BLOCKBUSTER | BLOG | BLUE | BOATS | BOM | BOO | BOOK | BOSTON | BOT | BOUTIQUE | BOX | BROADWAY | BROKER | BRUSSELS | BUDAPEST | BUILD | BUILDERS | BUSINESS | BUY | BUZZ | BY | BZ | BZH | CAB | CAFE | CALL | CAM | CAMERA | CAMP | CANCERRESEARCH | CAPETOWN | CAPITAL | CAR | CARDS | CARE | CAREER | CAREERS | CARS | CASA | CASE | CASEIH | CASH | CASINO | CAT | CATERING | CATHOLIC | CC | CEB | CENTER | CFD | CHANNEL | CHAT | CHEAP | CHRISTMAS | CHURCH | CIPRIANI | CIRCLE | CITY | CITYEATS | CLEANING | CLICK | CLINIC | CLINIQUE | CLOTHING | CLOUD | CLUB | CO | COACH | CODES | COFFEE | COLLEGE | COLOGNE | *COM | COMMUNITY | COMPANY | COMPARE | COMPUTER | CONDOS | CONSTRUCTION | CONSULTING | CONTACT | CONTRACTORS | COOKING | COOKINGCHANNEL | COOL | COOP | CORSICA | COUNTRY | COUPON | COUPONS | COURSES | CR | CREDIT | CREDITCARD | CRICKET | CRUISE | CRUISES | CX | CYMRU | CYOU | CZ | DAD | DANCE | DATA | DATE | DATING | DAY | DCLK | DDS | DEAL | DEALS | DEGREE | DELIVERY | DEMOCRAT | DENTAL | DENTIST | DESI | DESIGN | DEV | DIAMONDS | DIET | DIGITAL | DIRECT | DIRECTORY | DISCOUNT | DIY | DM | DO | DOCS | DOCTOR | DOG | DOMAINS | DOT | DOWNLOAD | DRIVE | DTV | DUBAI | DUCK | DURBAN | DVR | EARTH | EAT | ECO | EDUCATION | EMAIL | ENERGY | ENGINEER | ENGINEERING | ENTERPRISES | EQUIPMENT | ESQ | ESTATE | EUS | EVENTS | EXCHANGE | EXPERT | EXPOSED | EXPRESS | FAIL | FAITH | FAMILY | FAN | FANS | FARM | FASHION | FAST | FEEDBACK | FIDO | FILM | FINAL | FINANCE | FINANCIAL | FIRE | FISH | FISHING | FIT | FITNESS | FLIGHTS | FLORIST | FLOWERS | FLY | FO | FOO | FOOD | FOODNETWORK | FOOTBALL | FORSALE | FORUM | FOUNDATION | *FR | FREE | FRL | FRONTDOOR | FTR | FUN | FUND | FURNITURE | FUTBOL | FYI | GAL | GALLERY | GAME | GAMES | GARDEN | GD | GDN | GENT | GEORGE | GGEE | GH | GI | GIFT | GIFTS | GIVES | GL | GLOBAL | GMBH | GOLD | GOLF | GOO | GOP | GOT | GQ | GRATIS | GREEN | GRIPE | GROCERY | GROUP | GS | GUGE | GUIDE | GUITARS | GURU | GY | HAIR | HAMBURG | HANGOUT | HAUS | HEALTH | HEALTHCARE | HELP | HELSINKI | HERE | HGTV | HIV | HOCKEY | HOLDINGS | HOLIDAY | HOMEGOODS | HOMES | HOMESENSE | HORSE | HOSPITAL | HOST | HOSTING | HOT | HOTELES | HOTELS | HOUSE | HOW | HT | ICBC | ICU | IMAMAT | IMMO | IMMOBILIEN | INDUSTRIES | INFO | ING | INK | INSTITUTE | INSURANCE | INSURE | INTERNATIONAL | INVESTMENTS | IO | IRISH | ISMAILI | IST | ISTANBUL | JETZT | JEWELRY | JIO | JLL | JMP | JNJ | JOBS | JOBURG | JOT | JOY | JPRS | JUEGOS | KAUFEN | KIM | KITCHEN | KIWI | KN | KOELN | KOSHER | KPN | KRD | KW | KYOTO | LC | LEASE | LEFRAK | LEGAL | LGBT | LIFE | LIFEINSURANCE | LIGHTING | LIKE | LIMITED | LIMO | LINK | LIVE | LIVING | LOAN | LOANS | LOCKER | LOFT | LOL | LONDON | LOTTO | LOVE | LT | LTD | LTDA | LUXE | LUXURY | MADRID | MAISON | MAKEUP | MANAGEMENT | MAP | MARKET | MARKETING | MARKETS | MARSHALLS | MBA | ME | MED | MEDIA | MEET | MELBOURNE | MEME | MEMORIAL | MEN | MENU | MG | MIAMI | MINT | MK | ML | MLS | MN | MOBI | MOBILE | MODA | MOE | MOI | MOM | MONEY | MONSTER | MORTGAGE | MOSCOW | MOTORCYCLES | MOV | MOVIE | MR | MS | MU | MX | NAB | NAGOYA | NAME | NAVY | *NET | NETBANK | NETWORK | NEW | NEXT | NEXTDIRECT | NF | NG | NGO | nic | NINJA | NOW | NOWRUZ | NOWTV | NRW | NU | NYC | OBSERVER | OFF | OKINAWA | OLDNAVY | OLLO | ONE | ONG | ONL | ONLINE | ONYOURSIDE | OOO | OPEN | ORG | ORGANIC | ORIGINS | OSAKA | OTT | PAGE | PARIS | PARS | PARTNERS | PARTS | PARTY | PASSAGENS | PAY | PE | PET | PICS | PICTURES | PID | PIN | PINK | PIZZA | PLUMBING | PLUS | PM | PNC | POKER | PORN | PR | PRAMERICA | PRESS | PRIME | PRO | PRODUCTIONS | PROF | PROMO | PROPERTIES | PROPERTY | PROTECTION | PS | PUB | PW | QPON | QUEBEC | RACING | RADIO | RAID | RE | READ | REALESTATE | REALTOR | REALTY | RECIPES | RED | REHAB | REISE | REISEN | REIT | REN | RENT | RENTALS | REPAIR | REPORT | REPUBLICAN | REST | RESTAURANT | REVIEW | RICH | RICHARDLI | RIGHTATHOME | RIL | RIO | RIP | RO | ROCKS | RODEO | ROOM | RS | RSVP | RU | RUGBY | RUHR | RUN | RYUKYU | SAFE | SALE | SALON | SAMSCLUB | SARL | SAS | SAVE | SC | SCHOOL | SCHULE | SCIENCE | SCOT | SE | SEARCH | SECURE | SECURITY | SELECT | SERVICES | SEX | SEXY | SH | SHIA | SHIKSHA | SHOES | SHOP | SHOPPING | SHOW | SHOWTIME | SI | SILK | SINGLES | SITE | SK | SKI | SKIN | SL | SLING | SMILE | SO | SOCCER | SOCIAL | SOFTWARE | SOLUTIONS | SONG | SOY | SPACE | SPORT | SPOT | SPREADBETTING | SRL | ST | STOCKHOLM | STORAGE | STORE | STREAM | STUDIO | STUDY | STYLE | SU | SUCKS | SUPPLIES | SUPPLY | SUPPORT | SURF | SURGERY | SWISS | SX | SY | SYDNEY | SYSTEMS | TAB | TAIPEI | TALK | TATAR | TATTOO | TAX | TAXI | TC | TCI | TEAM | TECH | TECHNOLOGY | TENNIS | TF | THD | THEATER | THEATRE | TIAA | TICKETS | TIENDA | TIPS | TIRES | TIROL | TJMAXX | TKMAXX | TL | TMALL | TODAY | TOKYO | TOOLS | TOP | TOURS | TOWN | TOYS | TRADE | TRADING | TRAINING | TRAVELERSINSURANCE | TRUST | TRV | TUBE | TUNES | TUSHU | TV | UBANK | UNIVERSITY | UNO | US | UZ | VACATIONS | VANA | VC | VEGAS | VENTURES | VERSICHERUNG | VET | VIAJES | VIDEO | VIN | VIP | VISION | VIVA | VODKA | VOTE | VOTING | VOTO | VOYAGE | VUELOS | WALES | WANG | WANGGOU | WATCH | WATCHES | WEATHER | WEBCAM | WEBSITE | WED | WEDDING | WEIBO | WF | WIEN | WIKI | WIN | WINE | WINNERS | WORK | WORKS | WORLD | WOW | WTF | XIN | XN--1CK2E1B | XN--3BST00M | XN--3DS443G | XN--3OQ18VL8PN36A | XN--45Q11C | XN--5SU34J936BGSG | XN--5TZM5G | XN--6FRZ82G | XN--6QQ986B3XL | XN--80ADXHKS | XN--80AQECDR1A | XN--80ASEHDB | XN--80ASWG | XN--8Y0A063A | XN--9KRT00A | XN--B4W605FERD | XN--BCK1B9A5DRE4C | XN--CCK2B3B | XN--CZRS0T | XN--CZRU2D | XN--D1ACJ3B | XN--ECKVDTC9D | XN--ESTV75G | XN--FCT429K | XN--FIQ228C5HS | XN--FJQ720A | XN--FLW351E | XN--G2XX48C | XN--GCKR3F0F | XN--GK3AT1E | XN--HXT814E | XN--I1B6B1A6A2E | XN--JLQ61U9W7B | XN--JVR189M | XN--KCRX77D1X4A | XN--KPU716F | XN--KPUT3I | XN--MGBA3A3EJT | XN--MGBA7C0BBN0A | XN--MGBAAKC7DVF | XN--MGBAB2BD | XN--MGBCA7DZDO | XN--MGBI4ECEXP | XN--MGBT3DHD | XN--NGBC5AZD | XN--NGBE9E0A | XN--NQV7F | XN--NQV7FS00EMA | XN--NYQY26A | XN--Q9JYB4C | XN--QCKA1PMC | XN--RHQV96G | XN--SES554G | XN--UNUP4Y | XN--VERMGENSBERATER-CTB | XN--VERMGENSBERATUNG-PWB | XN--VHQUV | XN--W4R85EL8FHU5DNRA | XXX | XYZ | YACHTS | YOGA | YOKOHAMA | YOU | YT | ZM | ZONE | ZUERICH )

registrar=$(whois $1 | grep -i -m 1 "registrar:" | awk -F ":" '{print $2}');;

GAY | INC | LLC)
registrar=$(whois -h whois.nic.$tld $1 | grep -i -m 1 "registrar:" | awk -F ":" '{print $2}');;

#Et chaque TLD pas compatible...

FI)
registrar=$(whois $1 | egrep "registrar.*:" | awk -F ":" '{print $2}');;

IT)
registrar=$(whois $1 | grep -A 1 -i "registrar" | grep Organization | awk -F ":" '{print $2}');;

AS | CH | EE | GG | JE | LI | *UK)
registrar=$(whois $1 | grep -i -A 1 "registrar" | grep -v -i registrar | grep -v name);;

BE | EU)
registrar=$(whois $1 | grep -i -A 1 "registrar" | grep -i name | awk -F ":" '{print $2}');;

NL | PL)
registrar=$(whois $1 | grep -i -A 1 "registrar:" | grep -v -i "registrar");;
UA)
registrar=$(whois $1 | grep "registrar:"| awk -F ":" '{print $2}');;

AE)
registrar=$(whois $1 | grep "Registrar Name:"| awk -F ":" '{print $2}');;



# Pas de serveur whois
DE| AD | BA | AZ | BB | BO | BT | CG | CHARITY | CD | CN | CY | DK | EG | ES | EC | GA | GE | GOV | GP | GM | GR | GW | HM | INC | IN | JM | IQ | KI | LK | LS | MC | MIL | MW | MT | MV | MP | NI | PA | PK | PN | PY | SB | SV | TD | SS | TO | TT | VE | UY | VI | YE | ZA | HN )
registrar="Info non disponible dans le whois";;

# Pas de serveur whois, mais Freenom
TK | ML | CF | GQ )
registrar="Freenom (pas de serveur whois)";;


*)
#echo "still trying"
registrar=$(whois $1 | grep -i "registrar:") ;;
esac

if [[ $registrar == "" ]]; then
	registrar="Not Found"
fi 

			echo -e "<tr><td>$dn</td><td>$registrar</td></tr>"
}


while [ "$1" != "" ];do
	case $1 in
		-f)
			while read dn
			do 
			check $dn
			done < $2 
			shift
			shift ;;
		*)

			while [ "$1" != "" ]; do
			dn=$1
			check $dn
			shift
			done ;;
	esac
done

